{
  "api_key": "your-api-key",
  "base_url": "https://api.openai.com/v1",
  "siliconflow_api_key": "your-siliconflow-api-key",
  "deepseek_api_key": "your-Deepseek-api-key",
  "google_api_key": "your-google-api-key",
  "content_size_min": 750,
  "auto_continue": false,
  "platform_model_configs": {
    "step1": {
      "platform": "siliconflow",
      "model": "[16]千问"
    },
    "step2": {
      "platform": "siliconflow",
      "model": "[4]腾讯混元"
    },
    "step3": {
      "platform": "siliconflow",
      "model": "[16]千问"
    },
    "step4": {
      "platform": "siliconflow",
      "model": "[16]千问"
    },
    "step5": {
      "platform": "siliconflow",
      "model": "[4]千问长文"
    },
    "step6": {
      "platform": "siliconflow",
      "model": "[4]千问长文"
    },
    "step7": {
      "platform": "siliconflow",
      "model": "[16]千问"
    }
  }
}